project_id = "ojoenxchuzqonpixomkl"

[functions.ai-chat]
verify_jwt = true

[functions.profiles-get-me]
verify_jwt = true

[functions.profiles-update-me]
verify_jwt = true

[functions.profiles-update-points]
verify_jwt = true
